name: raktadaan
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  flutter:
    sdk: flutter
  
  get: ^4.6.6
  shared_preferences: ^2.2.2
  email_validator: '^2.1.16'
  cloud_firestore: ^4.12.2
  geocoding: ^2.1.1
  geocode: ^1.0.3
  google_sign_in: ^6.1.5
  flutter_svg: ^0.22.0
  url_launcher: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
