name: raktadaan
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.6.0

  get: ^4.6.6
  shared_preferences: ^2.2.2
  email_validator: '^2.1.16'
  cloud_firestore: ^4.12.2
  geocoding: ^2.1.1
  geocode: ^1.0.3
  google_sign_in: ^6.1.5
  flutter_svg: ^0.22.0
  url_launcher: ^6.2.1
  flutter_map: ^5.0.0
  geoflutterfire2: ^2.3.15
  geolocator: ^10.0.1
  latlong2: ^0.9.0
  path: ^1.8.3
  image_picker: ^1.0.6
  timeago: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
