name: Build and Release APK

on:
  push:
    branches: '*'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v5

      - name: Get Commit Hash
        id: commit
        run: echo "::set-output name=commitHash::${{ github.sha }}"

      - name: Extract Version Name
        id: version
        run: echo "::set-output name=versionName::${{ steps.commit.outputs.commitHash:0:4 }}"

      - name: Build APK
        run: flutter build apk

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/raktadaan-${{ steps.version.outputs.versionName }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/raktadaan-${{ steps.version.outputs.versionName }}.apk
